
version: '3.1'
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    container_name: mongo
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: develop_user
      MONGO_INITDB_ROOT_PASSWORD: develop_password
    ports:
      - "27017:27017"