version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'develop'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'develop_user'
      MYSQL_PASSWORD: 'develop_password'
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - 3306:3306
