services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: develop_user 
      POSTGRES_PASSWORD: develop_password
      POSTGRES_DB: develop
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
